name: Release Container Image

on:
  workflow_dispatch:
  push:
    tags:
      - "webapp@*"
      - "api@*"
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "LICENSE"
      - "tests/**"
      - ".husky/**"
      - ".changeset/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "LICENSE"
      - "tests/**"
      - ".husky/**"
      - ".changeset/**"

permissions: read-all

env:
  CI: true
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_BUILDKIT: "1"

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: docker-security
        uses: instrumenta/conftest-action@master
        with:
          files: Dockerfile
          policy: .docker-security.rego

  container-webapp:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/main' ||
      startsWith(github.ref, 'refs/tags/webapp@') ||
      github.event_name == 'pull_request'
    permissions:
      contents: read
      packages: write
    needs:
      - security

    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Github Container registry
        uses: docker/login-action@v3.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine version
        id: version
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "value=latest" >> "$GITHUB_OUTPUT"
          elif [[ "${{ github.ref }}" =~ ^refs/tags/webapp@(.+)$ ]]; then
            echo "value=${BASH_REMATCH[1]}" >> "$GITHUB_OUTPUT"
          fi

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5.8.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          labels: |
            maintainer=teamdigitale
            org.opencontainers.image.title=dati-semantic-schema-editor
          tags: |
            type=raw,value={{date 'YYYYMMDD'}}-${{github.run_number}}-{{sha}}
            type=raw,value=${{ steps.version.outputs.value }},enable=${{ steps.version.outputs.value != '' }}

      - name: Build and push
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          target: webapp
          push: ${{ github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'push-container:webapp') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  container-api:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/main' ||
      startsWith(github.ref, 'refs/tags/api@') ||
      github.event_name == 'pull_request'
    permissions:
      contents: read
      packages: write
    needs:
      - security

    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Github Container registry
        uses: docker/login-action@v3.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine version
        id: version
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "value=latest" >> "$GITHUB_OUTPUT"
          elif [[ "${{ github.ref }}" =~ ^refs/tags/api@(.+)$ ]]; then
            echo "value=${BASH_REMATCH[1]}" >> "$GITHUB_OUTPUT"
          fi

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5.8.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-api
          labels: |
            maintainer=teamdigitale
            org.opencontainers.image.title=dati-semantic-schema-editor-api
          tags: |
            type=raw,value={{date 'YYYYMMDD'}}-${{github.run_number}}-{{sha}}
            type=raw,value=${{ steps.version.outputs.value }},enable=${{ steps.version.outputs.value != '' }}

      - name: Build and push
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          target: api
          push: ${{ github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'push-container:api') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
